spring:
    application:
        name: summer
    datasource:
        url: jdbc:mysql://localhost:3306/user2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: Lzh20050318!
        driver-class-name: com.mysql.cj.jdbc.Driver
    security:
        user:
            name: admin
            password: password
server:
    port: 7395

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
    secret: "your-secret-key-must-be-at-least-256-bits-long"
    expiration: 86400000  # 24小时 (毫秒)
logging:
    charset:
        console: utf-8
app:
  upload:
    dir: "D:/jweb-endwork/uploads"
    url-path: "/api/upfile"
